In [22]:
import pandas as pd

df = pd.read_csv('Pokemon.csv')

df

print(df.head())

   #        Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1   Bulbasaur  Grass  Poison    318  45      49       49       65       65
1  2     Ivysaur  Grass  Poison    405  60      62       63       80       80
2  3    Venusaur  Grass  Poison    525  80      82       83      100      100
3  4  Charmander   Fire     NaN    309  39      52       43       60       50
4  5  Charmeleon   Fire     NaN    405  58      64       58       80       65

   Speed  Stage  Legendary
0     45      1      False
1     60      2      False
2     80      3      False
3     65      1      False
4     80      2      False

In [23]:
print(df.to_string())

       #        Name    Type 1    Type 2  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Stage  Legendary
0      1   Bulbasaur     Grass    Poison    318   45      49       49       65       65     45      1      False
1      2     Ivysaur     Grass    Poison    405   60      62       63       80       80     60      2      False
2      3    Venusaur     Grass    Poison    525   80      82       83      100      100     80      3      False
3      4  Charmander      Fire       NaN    309   39      52       43       60       50     65      1      False
4      5  Charmeleon      Fire       NaN    405   58      64       58       80       65     80      2      False
5      6   Charizard      Fire    Flying    534   78      84       78      109       85    100      3      False
6      7    Squirtle     Water       NaN    314   44      48       65       50       64     43      1      False
7      8   Wartortle     Water       NaN    405   59      63       80       65       80     58      2      False
8      9   Blastoise     Water       NaN    530   79      83      100       85      105     78      3      False
9     10    Caterpie       Bug       NaN    195   45      30       35       20       20     45      1      False
10    11     Metapod       Bug       NaN    205   50      20       55       25       25     30      2      False
11    12  Butterfree       Bug    Flying    395   60      45       50       90       80     70      3      False
12    13      Weedle       Bug    Poison    195   40      35       30       20       20     50      1      False
13    14      Kakuna       Bug    Poison    205   45      25       50       25       25     35      2      False
14    15    Beedrill       Bug    Poison    395   65      90       40       45       80     75      3      False
15    16      Pidgey    Normal    Flying    251   40      45       40       35       35     56      1      False
16    17   Pidgeotto    Normal    Flying    349   63      60       55       50       50     71      2      False
17    18     Pidgeot    Normal    Flying    479   83      80       75       70       70    101      3      False
18    19     Rattata    Normal       NaN    253   30      56       35       25       35     72      1      False
19    20    Raticate    Normal       NaN    413   55      81       60       50       70     97      2      False
20    21     Spearow    Normal    Flying    262   40      60       30       31       31     70      1      False
21    22      Fearow    Normal    Flying    442   65      90       65       61       61    100      2      False
22    23       Ekans    Poison       NaN    288   35      60       44       40       54     55      1      False
23    24       Arbok    Poison       NaN    438   60      85       69       65       79     80      2      False
24    25     Pikachu  Electric       NaN    320   35      55       40       50       50     90      1      False
25    26      Raichu  Electric       NaN    485   60      90       55       90       80    110      2      False
26    27   Sandshrew    Ground       NaN    300   50      75       85       20       30     40      1      False
27    28   Sandslash    Ground       NaN    450   75     100      110       45       55     65      2      False
28    29     Nidoran    Poison       NaN    275   55      47       52       40       40     41      1      False
29    30    Nidorina    Poison       NaN    365   70      62       67       55       55     56      2      False
30    31   Nidoqueen    Poison    Ground    505   90      92       87       75       85     76      3      False
31    32     Nidoran    Poison       NaN    273   46      57       40       40       40     50      1      False
32    33    Nidorino    Poison       NaN    365   61      72       57       55       55     65      2      False
33    34    Nidoking    Poison    Ground    505   81     102       77       85       75     85      3      False
34    35    Clefairy     Fairy       NaN    323   70      45       48       60       65     35      1      False
35    36    Clefable     Fairy       NaN    483   95      70       73       95       90     60      2      False
36    37      Vulpix      Fire       NaN    299   38      41       40       50       65     65      1      False
37    38   Ninetales      Fire       NaN    505   73      76       75       81      100    100      2      False
38    39  Jigglypuff    Normal     Fairy    270  115      45       20       45       25     20      1      False
39    40  Wigglytuff    Normal     Fairy    435  140      70       45       85       50     45      2      False
40    41       Zubat    Poison    Flying    245   40      45       35       30       40     55      1      False
41    42      Golbat    Poison    Flying    455   75      80       70       65       75     90      2      False
42    43      Oddish     Grass    Poison    320   45      50       55       75       65     30      1      False
43    44       Gloom     Grass    Poison    395   60      65       70       85       75     40      2      False
44    45   Vileplume     Grass    Poison    490   75      80       85      110       90     50      3      False
45    46       Paras       Bug     Grass    285   35      70       55       45       55     25      1      False
46    47    Parasect       Bug     Grass    405   60      95       80       60       80     30      2      False
47    48     Venonat       Bug    Poison    305   60      55       50       40       55     45      1      False
48    49    Venomoth       Bug    Poison    450   70      65       60       90       75     90      2      False
49    50     Diglett    Ground       NaN    265   10      55       25       35       45     95      1      False
50    51     Dugtrio    Ground       NaN    405   35      80       50       50       70    120      2      False
51    52      Meowth    Normal       NaN    290   40      45       35       40       40     90      1      False
52    53     Persian    Normal       NaN    440   65      70       60       65       65    115      2      False
53    54     Psyduck     Water       NaN    320   50      52       48       65       50     55      1      False
54    55     Golduck     Water       NaN    500   80      82       78       95       80     85      2      False
55    56      Mankey  Fighting       NaN    305   40      80       35       35       45     70      1      False
56    57    Primeape  Fighting       NaN    455   65     105       60       60       70     95      2      False
57    58   Growlithe      Fire       NaN    350   55      70       45       70       50     60      1      False
58    59    Arcanine      Fire       NaN    555   90     110       80      100       80     95      2      False
59    60     Poliwag     Water       NaN    300   40      50       40       40       40     90      1      False
60    61   Poliwhirl     Water       NaN    385   65      65       65       50       50     90      2      False
61    62   Poliwrath     Water  Fighting    510   90      95       95       70       90     70      3      False
62    63        Abra   Psychic       NaN    310   25      20       15      105       55     90      1      False
63    64     Kadabra   Psychic       NaN    400   40      35       30      120       70    105      2      False
64    65    Alakazam   Psychic       NaN    500   55      50       45      135       95    120      3      False
65    66      Machop  Fighting       NaN    305   70      80       50       35       35     35      1      False
66    67     Machoke  Fighting       NaN    405   80     100       70       50       60     45      2      False
67    68     Machamp  Fighting       NaN    505   90     130       80       65       85     55      3      False
68    69  Bellsprout     Grass    Poison    300   50      75       35       70       30     40      1      False
69    70  Weepinbell     Grass    Poison    390   65      90       50       85       45     55      2      False
70    71  Victreebel     Grass    Poison    490   80     105       65      100       70     70      3      False
71    72   Tentacool     Water    Poison    335   40      40       35       50      100     70      1      False
72    73  Tentacruel     Water    Poison    515   80      70       65       80      120    100      2      False
73    74     Geodude      Rock    Ground    300   40      80      100       30       30     20      1      False
74    75    Graveler      Rock    Ground    390   55      95      115       45       45     35      2      False
75    76       Golem      Rock    Ground    495   80     120      130       55       65     45      3      False
76    77      Ponyta      Fire       NaN    410   50      85       55       65       65     90      1      False
77    78    Rapidash      Fire       NaN    500   65     100       70       80       80    105      2      False
78    79    Slowpoke     Water   Psychic    315   90      65       65       40       40     15      1      False
79    80     Slowbro     Water   Psychic    490   95      75      110      100       80     30      2      False
80    81   Magnemite  Electric     Steel    325   25      35       70       95       55     45      1      False
81    82    Magneton  Electric     Steel    465   50      60       95      120       70     70      2      False
82    83  Farfetch'd    Normal    Flying    352   52      65       55       58       62     60      1      False
83    84       Doduo    Normal    Flying    310   35      85       45       35       35     75      1      False
84    85      Dodrio    Normal    Flying    460   60     110       70       60       60    100      2      False
85    86        Seel     Water       NaN    325   65      45       55       45       70     45      1      False
86    87     Dewgong     Water       Ice    475   90      70       80       70       95     70      2      False
87    88      Grimer    Poison       NaN    325   80      80       50       40       50     25      1      False
88    89         Muk    Poison       NaN    500  105     105       75       65      100     50      2      False
89    90    Shellder     Water       NaN    305   30      65      100       45       25     40      1      False
90    91    Cloyster     Water       Ice    525   50      95      180       85       45     70      2      False
91    92      Gastly     Ghost    Poison    310   30      35       30      100       35     80      1      False
92    93     Haunter     Ghost    Poison    405   45      50       45      115       55     95      2      False
93    94      Gengar     Ghost    Poison    500   60      65       60      130       75    110      3      False
94    95        Onix      Rock    Ground    385   35      45      160       30       45     70      1      False
95    96     Drowzee   Psychic       NaN    328   60      48       45       43       90     42      1      False
96    97       Hypno   Psychic       NaN    483   85      73       70       73      115     67      2      False
97    98      Krabby     Water       NaN    325   30     105       90       25       25     50      1      False
98    99     Kingler     Water       NaN    475   55     130      115       50       50     75      2      False
99   100     Voltorb  Electric       NaN    330   40      30       50       55       55    100      1      False
100  101   Electrode  Electric       NaN    480   60      50       70       80       80    140      2      False
101  102   Exeggcute     Grass   Psychic    325   60      40       80       60       45     40      1      False
102  103   Exeggutor     Grass   Psychic    520   95      95       85      125       65     55      2      False
103  104      Cubone    Ground       NaN    320   50      50       95       40       50     35      1      False
104  105     Marowak    Ground       NaN    425   60      80      110       50       80     45      2      False
105  106   Hitmonlee  Fighting       NaN    455   50     120       53       35      110     87      1      False
106  107  Hitmonchan  Fighting       NaN    455   50     105       79       35      110     76      1      False
107  108   Lickitung    Normal       NaN    385   90      55       75       60       75     30      1      False
108  109     Koffing    Poison       NaN    340   40      65       95       60       45     35      1      False
109  110     Weezing    Poison       NaN    490   65      90      120       85       70     60      2      False
110  111     Rhyhorn    Ground      Rock    345   80      85       95       30       30     25      1      False
111  112      Rhydon    Ground      Rock    485  105     130      120       45       45     40      2      False
112  113     Chansey    Normal       NaN    450  250       5        5       35      105     50      1      False
113  114     Tangela     Grass       NaN    435   65      55      115      100       40     60      1      False
114  115  Kangaskhan    Normal       NaN    490  105      95       80       40       80     90      1      False
115  116      Horsea     Water       NaN    295   30      40       70       70       25     60      1      False
116  117      Seadra     Water       NaN    440   55      65       95       95       45     85      2      False
117  118     Goldeen     Water       NaN    320   45      67       60       35       50     63      1      False
118  119     Seaking     Water       NaN    450   80      92       65       65       80     68      2      False
119  120      Staryu     Water       NaN    340   30      45       55       70       55     85      1      False
120  121     Starmie     Water   Psychic    520   60      75       85      100       85    115      2      False
121  122    Mr. Mime   Psychic     Fairy    460   40      45       65      100      120     90      1      False
122  123     Scyther       Bug    Flying    500   70     110       80       55       80    105      1      False
123  124        Jynx       Ice   Psychic    455   65      50       35      115       95     95      1      False
124  125  Electabuzz  Electric       NaN    490   65      83       57       95       85    105      1      False
125  126      Magmar      Fire       NaN    495   65      95       57      100       85     93      1      False
126  127      Pinsir       Bug       NaN    500   65     125      100       55       70     85      1      False
127  128      Tauros    Normal       NaN    490   75     100       95       40       70    110      1      False
128  129    Magikarp     Water       NaN    200   20      10       55       15       20     80      1      False
129  130    Gyarados     Water    Flying    540   95     125       79       60      100     81      2      False
130  131      Lapras     Water       Ice    535  130      85       80       85       95     60      1      False
131  132       Ditto    Normal       NaN    288   48      48       48       48       48     48      1      False
132  133       Eevee    Normal       NaN    325   55      55       50       45       65     55      1      False
133  134    Vaporeon     Water       NaN    525  130      65       60      110       95     65      2      False
134  135     Jolteon  Electric       NaN    525   65      65       60      110       95    130      2      False
135  136     Flareon      Fire       NaN    525   65     130       60       95      110     65      2      False
136  137     Porygon    Normal       NaN    395   65      60       70       85       75     40      1      False
137  138     Omanyte      Rock     Water    355   35      40      100       90       55     35      1      False
138  139     Omastar      Rock     Water    495   70      60      125      115       70     55      2      False
139  140      Kabuto      Rock     Water    355   30      80       90       55       45     55      1      False
140  141    Kabutops      Rock     Water    495   60     115      105       65       70     80      2      False
141  142  Aerodactyl      Rock    Flying    515   80     105       65       60       75    130      1      False
142  143     Snorlax    Normal       NaN    540  160     110       65       65      110     30      1      False
143  144    Articuno       Ice    Flying    580   90      85      100       95      125     85      1       True
144  145      Zapdos  Electric    Flying    580   90      90       85      125       90    100      1       True
145  146     Moltres      Fire    Flying    580   90     100       90      125       85     90      1       True
146  147     Dratini    Dragon       NaN    300   41      64       45       50       50     50      1      False
147  148   Dragonair    Dragon       NaN    420   61      84       65       70       70     70      2      False
148  149   Dragonite    Dragon    Flying    600   91     134       95      100      100     80      3      False
149  150      Mewtwo   Psychic       NaN    680  106     110       90      154       90    130      1       True
150  151         Mew   Psychic       NaN    600  100     100      100      100      100    100      1      False

In [10]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Stage', 'Legendary'],
      dtype='object')

In [12]:
df['Name'][0:5]

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: object

In [16]:
print(df[['Name', 'Type 1', 'HP']][0:5])

         Name Type 1  HP
0   Bulbasaur  Grass  45
1     Ivysaur  Grass  60
2    Venusaur  Grass  80
3  Charmander   Fire  39
4  Charmeleon   Fire  58

In [18]:
print(df.iloc[0:3])

   #       Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1  Bulbasaur  Grass  Poison    318  45      49       49       65       65
1  2    Ivysaur  Grass  Poison    405  60      62       63       80       80
2  3   Venusaur  Grass  Poison    525  80      82       83      100      100

   Speed  Stage  Legendary
0     45      1      False
1     60      2      False
2     80      3      False

In [19]:
print(df.iloc[2,1])

Venusaur

In [20]:
for index, row in df.iterrows():
    print(index, row)

0 #                    1
Name         Bulbasaur
Type 1           Grass
Type 2          Poison
Total              318
HP                  45
Attack              49
Defense             49
Sp. Atk             65
Sp. Def             65
Speed               45
Stage                1
Legendary        False
Name: 0, dtype: object
1 #                  2
Name         Ivysaur
Type 1         Grass
Type 2        Poison
Total            405
HP                60
Attack            62
Defense           63
Sp. Atk           80
Sp. Def           80
Speed             60
Stage              2
Legendary      False
Name: 1, dtype: object
2 #                   3
Name         Venusaur
Type 1          Grass
Type 2         Poison
Total             525
HP                 80
Attack             82
Defense            83
Sp. Atk           100
Sp. Def           100
Speed              80
Stage               3
Legendary       False
Name: 2, dtype: object
3 #                     4
Name         Charmander
Type 1             Fire
Type 2              NaN
Total               309
HP                   39
Attack               52
Defense              43
Sp. Atk              60
Sp. Def              50
Speed                65
Stage                 1
Legendary         False
Name: 3, dtype: object
4 #                     5
Name         Charmeleon
Type 1             Fire
Type 2              NaN
Total               405
HP                   58
Attack               64
Defense              58
Sp. Atk              80
Sp. Def              65
Speed                80
Stage                 2
Legendary         False
Name: 4, dtype: object
5 #                    6
Name         Charizard
Type 1            Fire
Type 2          Flying
Total              534
HP                  78
Attack              84
Defense             78
Sp. Atk            109
Sp. Def             85
Speed              100
Stage                3
Legendary        False
Name: 5, dtype: object
6 #                   7
Name         Squirtle
Type 1          Water
Type 2            NaN
Total             314
HP                 44
Attack             48
Defense            65
Sp. Atk            50
Sp. Def            64
Speed              43
Stage               1
Legendary       False
Name: 6, dtype: object
7 #                    8
Name         Wartortle
Type 1           Water
Type 2             NaN
Total              405
HP                  59
Attack              63
Defense             80
Sp. Atk             65
Sp. Def             80
Speed               58
Stage                2
Legendary        False
Name: 7, dtype: object
8 #                    9
Name         Blastoise
Type 1           Water
Type 2             NaN
Total              530
HP                  79
Attack              83
Defense            100
Sp. Atk             85
Sp. Def            105
Speed               78
Stage                3
Legendary        False
Name: 8, dtype: object
9 #                  10
Name         Caterpie
Type 1            Bug
Type 2            NaN
Total             195
HP                 45
Attack             30
Defense            35
Sp. Atk            20
Sp. Def            20
Speed              45
Stage               1
Legendary       False
Name: 9, dtype: object
10 #                 11
Name         Metapod
Type 1           Bug
Type 2           NaN
Total            205
HP                50
Attack            20
Defense           55
Sp. Atk           25
Sp. Def           25
Speed             30
Stage              2
Legendary      False
Name: 10, dtype: object
11 #                    12
Name         Butterfree
Type 1              Bug
Type 2           Flying
Total               395
HP                   60
Attack               45
Defense              50
Sp. Atk              90
Sp. Def              80
Speed                70
Stage                 3
Legendary         False
Name: 11, dtype: object
12 #                13
Name         Weedle
Type 1          Bug
Type 2       Poison
Total           195
HP               40
Attack           35
Defense          30
Sp. Atk          20
Sp. Def          20
Speed            50
Stage             1
Legendary     False
Name: 12, dtype: object
13 #                14
Name         Kakuna
Type 1          Bug
Type 2       Poison
Total           205
HP               45
Attack           25
Defense          50
Sp. Atk          25
Sp. Def          25
Speed            35
Stage             2
Legendary     False
Name: 13, dtype: object
14 #                  15
Name         Beedrill
Type 1            Bug
Type 2         Poison
Total             395
HP                 65
Attack             90
Defense            40
Sp. Atk            45
Sp. Def            80
Speed              75
Stage               3
Legendary       False
Name: 14, dtype: object
15 #                16
Name         Pidgey
Type 1       Normal
Type 2       Flying
Total           251
HP               40
Attack           45
Defense          40
Sp. Atk          35
Sp. Def          35
Speed            56
Stage             1
Legendary     False
Name: 15, dtype: object
16 #                   17
Name         Pidgeotto
Type 1          Normal
Type 2          Flying
Total              349
HP                  63
Attack              60
Defense             55
Sp. Atk             50
Sp. Def             50
Speed               71
Stage                2
Legendary        False
Name: 16, dtype: object
17 #                 18
Name         Pidgeot
Type 1        Normal
Type 2        Flying
Total            479
HP                83
Attack            80
Defense           75
Sp. Atk           70
Sp. Def           70
Speed            101
Stage              3
Legendary      False
Name: 17, dtype: object
18 #                 19
Name         Rattata
Type 1        Normal
Type 2           NaN
Total            253
HP                30
Attack            56
Defense           35
Sp. Atk           25
Sp. Def           35
Speed             72
Stage              1
Legendary      False
Name: 18, dtype: object
19 #                  20
Name         Raticate
Type 1         Normal
Type 2            NaN
Total             413
HP                 55
Attack             81
Defense            60
Sp. Atk            50
Sp. Def            70
Speed              97
Stage               2
Legendary       False
Name: 19, dtype: object
20 #                 21
Name         Spearow
Type 1        Normal
Type 2        Flying
Total            262
HP                40
Attack            60
Defense           30
Sp. Atk           31
Sp. Def           31
Speed             70
Stage              1
Legendary      False
Name: 20, dtype: object
21 #                22
Name         Fearow
Type 1       Normal
Type 2       Flying
Total           442
HP               65
Attack           90
Defense          65
Sp. Atk          61
Sp. Def          61
Speed           100
Stage             2
Legendary     False
Name: 21, dtype: object
22 #                23
Name          Ekans
Type 1       Poison
Type 2          NaN
Total           288
HP               35
Attack           60
Defense          44
Sp. Atk          40
Sp. Def          54
Speed            55
Stage             1
Legendary     False
Name: 22, dtype: object
23 #                24
Name          Arbok
Type 1       Poison
Type 2          NaN
Total           438
HP               60
Attack           85
Defense          69
Sp. Atk          65
Sp. Def          79
Speed            80
Stage             2
Legendary     False
Name: 23, dtype: object
24 #                  25
Name          Pikachu
Type 1       Electric
Type 2            NaN
Total             320
HP                 35
Attack             55
Defense            40
Sp. Atk            50
Sp. Def            50
Speed              90
Stage               1
Legendary       False
Name: 24, dtype: object
25 #                  26
Name           Raichu
Type 1       Electric
Type 2            NaN
Total             485
HP                 60
Attack             90
Defense            55
Sp. Atk            90
Sp. Def            80
Speed             110
Stage               2
Legendary       False
Name: 25, dtype: object
26 #                   27
Name         Sandshrew
Type 1          Ground
Type 2             NaN
Total              300
HP                  50
Attack              75
Defense             85
Sp. Atk             20
Sp. Def             30
Speed               40
Stage                1
Legendary        False
Name: 26, dtype: object
27 #                   28
Name         Sandslash
Type 1          Ground
Type 2             NaN
Total              450
HP                  75
Attack             100
Defense            110
Sp. Atk             45
Sp. Def             55
Speed               65
Stage                2
Legendary        False
Name: 27, dtype: object
28 #                 29
Name         Nidoran
Type 1        Poison
Type 2           NaN
Total            275
HP                55
Attack            47
Defense           52
Sp. Atk           40
Sp. Def           40
Speed             41
Stage              1
Legendary      False
Name: 28, dtype: object
29 #                  30
Name         Nidorina
Type 1         Poison
Type 2            NaN
Total             365
HP                 70
Attack             62
Defense            67
Sp. Atk            55
Sp. Def            55
Speed              56
Stage               2
Legendary       False
Name: 29, dtype: object
30 #                   31
Name         Nidoqueen
Type 1          Poison
Type 2          Ground
Total              505
HP                  90
Attack              92
Defense             87
Sp. Atk             75
Sp. Def             85
Speed               76
Stage                3
Legendary        False
Name: 30, dtype: object
31 #                 32
Name         Nidoran
Type 1        Poison
Type 2           NaN
Total            273
HP                46
Attack            57
Defense           40
Sp. Atk           40
Sp. Def           40
Speed             50
Stage              1
Legendary      False
Name: 31, dtype: object
32 #                  33
Name         Nidorino
Type 1         Poison
Type 2            NaN
Total             365
HP                 61
Attack             72
Defense            57
Sp. Atk            55
Sp. Def            55
Speed              65
Stage               2
Legendary       False
Name: 32, dtype: object
33 #                  34
Name         Nidoking
Type 1         Poison
Type 2         Ground
Total             505
HP                 81
Attack            102
Defense            77
Sp. Atk            85
Sp. Def            75
Speed              85
Stage               3
Legendary       False
Name: 33, dtype: object
34 #                  35
Name         Clefairy
Type 1          Fairy
Type 2            NaN
Total             323
HP                 70
Attack             45
Defense            48
Sp. Atk            60
Sp. Def            65
Speed              35
Stage               1
Legendary       False
Name: 34, dtype: object
35 #                  36
Name         Clefable
Type 1          Fairy
Type 2            NaN
Total             483
HP                 95
Attack             70
Defense            73
Sp. Atk            95
Sp. Def            90
Speed              60
Stage               2
Legendary       False
Name: 35, dtype: object
36 #                37
Name         Vulpix
Type 1         Fire
Type 2          NaN
Total           299
HP               38
Attack           41
Defense          40
Sp. Atk          50
Sp. Def          65
Speed            65
Stage             1
Legendary     False
Name: 36, dtype: object
37 #                   38
Name         Ninetales
Type 1            Fire
Type 2             NaN
Total              505
HP                  73
Attack              76
Defense             75
Sp. Atk             81
Sp. Def            100
Speed              100
Stage                2
Legendary        False
Name: 37, dtype: object
38 #                    39
Name         Jigglypuff
Type 1           Normal
Type 2            Fairy
Total               270
HP                  115
Attack               45
Defense              20
Sp. Atk              45
Sp. Def              25
Speed                20
Stage                 1
Legendary         False
Name: 38, dtype: object
39 #                    40
Name         Wigglytuff
Type 1           Normal
Type 2            Fairy
Total               435
HP                  140
Attack               70
Defense              45
Sp. Atk              85
Sp. Def              50
Speed                45
Stage                 2
Legendary         False
Name: 39, dtype: object
40 #                41
Name          Zubat
Type 1       Poison
Type 2       Flying
Total           245
HP               40
Attack           45
Defense          35
Sp. Atk          30
Sp. Def          40
Speed            55
Stage             1
Legendary     False
Name: 40, dtype: object
41 #                42
Name         Golbat
Type 1       Poison
Type 2       Flying
Total           455
HP               75
Attack           80
Defense          70
Sp. Atk          65
Sp. Def          75
Speed            90
Stage             2
Legendary     False
Name: 41, dtype: object
42 #                43
Name         Oddish
Type 1        Grass
Type 2       Poison
Total           320
HP               45
Attack           50
Defense          55
Sp. Atk          75
Sp. Def          65
Speed            30
Stage             1
Legendary     False
Name: 42, dtype: object
43 #                44
Name          Gloom
Type 1        Grass
Type 2       Poison
Total           395
HP               60
Attack           65
Defense          70
Sp. Atk          85
Sp. Def          75
Speed            40
Stage             2
Legendary     False
Name: 43, dtype: object
44 #                   45
Name         Vileplume
Type 1           Grass
Type 2          Poison
Total              490
HP                  75
Attack              80
Defense             85
Sp. Atk            110
Sp. Def             90
Speed               50
Stage                3
Legendary        False
Name: 44, dtype: object
45 #               46
Name         Paras
Type 1         Bug
Type 2       Grass
Total          285
HP              35
Attack          70
Defense         55
Sp. Atk         45
Sp. Def         55
Speed           25
Stage            1
Legendary    False
Name: 45, dtype: object
46 #                  47
Name         Parasect
Type 1            Bug
Type 2          Grass
Total             405
HP                 60
Attack             95
Defense            80
Sp. Atk            60
Sp. Def            80
Speed              30
Stage               2
Legendary       False
Name: 46, dtype: object
47 #                 48
Name         Venonat
Type 1           Bug
Type 2        Poison
Total            305
HP                60
Attack            55
Defense           50
Sp. Atk           40
Sp. Def           55
Speed             45
Stage              1
Legendary      False
Name: 47, dtype: object
48 #                  49
Name         Venomoth
Type 1            Bug
Type 2         Poison
Total             450
HP                 70
Attack             65
Defense            60
Sp. Atk            90
Sp. Def            75
Speed              90
Stage               2
Legendary       False
Name: 48, dtype: object
49 #                 50
Name         Diglett
Type 1        Ground
Type 2           NaN
Total            265
HP                10
Attack            55
Defense           25
Sp. Atk           35
Sp. Def           45
Speed             95
Stage              1
Legendary      False
Name: 49, dtype: object
50 #                 51
Name         Dugtrio
Type 1        Ground
Type 2           NaN
Total            405
HP                35
Attack            80
Defense           50
Sp. Atk           50
Sp. Def           70
Speed            120
Stage              2
Legendary      False
Name: 50, dtype: object
51 #                52
Name         Meowth
Type 1       Normal
Type 2          NaN
Total           290
HP               40
Attack           45
Defense          35
Sp. Atk          40
Sp. Def          40
Speed            90
Stage             1
Legendary     False
Name: 51, dtype: object
52 #                 53
Name         Persian
Type 1        Normal
Type 2           NaN
Total            440
HP                65
Attack            70
Defense           60
Sp. Atk           65
Sp. Def           65
Speed            115
Stage              2
Legendary      False
Name: 52, dtype: object
53 #                 54
Name         Psyduck
Type 1         Water
Type 2           NaN
Total            320
HP                50
Attack            52
Defense           48
Sp. Atk           65
Sp. Def           50
Speed             55
Stage              1
Legendary      False
Name: 53, dtype: object
54 #                 55
Name         Golduck
Type 1         Water
Type 2           NaN
Total            500
HP                80
Attack            82
Defense           78
Sp. Atk           95
Sp. Def           80
Speed             85
Stage              2
Legendary      False
Name: 54, dtype: object
55 #                  56
Name           Mankey
Type 1       Fighting
Type 2            NaN
Total             305
HP                 40
Attack             80
Defense            35
Sp. Atk            35
Sp. Def            45
Speed              70
Stage               1
Legendary       False
Name: 55, dtype: object
56 #                  57
Name         Primeape
Type 1       Fighting
Type 2            NaN
Total             455
HP                 65
Attack            105
Defense            60
Sp. Atk            60
Sp. Def            70
Speed              95
Stage               2
Legendary       False
Name: 56, dtype: object
57 #                   58
Name         Growlithe
Type 1            Fire
Type 2             NaN
Total              350
HP                  55
Attack              70
Defense             45
Sp. Atk             70
Sp. Def             50
Speed               60
Stage                1
Legendary        False
Name: 57, dtype: object
58 #                  59
Name         Arcanine
Type 1           Fire
Type 2            NaN
Total             555
HP                 90
Attack            110
Defense            80
Sp. Atk           100
Sp. Def            80
Speed              95
Stage               2
Legendary       False
Name: 58, dtype: object
59 #                 60
Name         Poliwag
Type 1         Water
Type 2           NaN
Total            300
HP                40
Attack            50
Defense           40
Sp. Atk           40
Sp. Def           40
Speed             90
Stage              1
Legendary      False
Name: 59, dtype: object
60 #                   61
Name         Poliwhirl
Type 1           Water
Type 2             NaN
Total              385
HP                  65
Attack              65
Defense             65
Sp. Atk             50
Sp. Def             50
Speed               90
Stage                2
Legendary        False
Name: 60, dtype: object
61 #                   62
Name         Poliwrath
Type 1           Water
Type 2        Fighting
Total              510
HP                  90
Attack              95
Defense             95
Sp. Atk             70
Sp. Def             90
Speed               70
Stage                3
Legendary        False
Name: 61, dtype: object
62 #                 63
Name            Abra
Type 1       Psychic
Type 2           NaN
Total            310
HP                25
Attack            20
Defense           15
Sp. Atk          105
Sp. Def           55
Speed             90
Stage              1
Legendary      False
Name: 62, dtype: object
63 #                 64
Name         Kadabra
Type 1       Psychic
Type 2           NaN
Total            400
HP                40
Attack            35
Defense           30
Sp. Atk          120
Sp. Def           70
Speed            105
Stage              2
Legendary      False
Name: 63, dtype: object
64 #                  65
Name         Alakazam
Type 1        Psychic
Type 2            NaN
Total             500
HP                 55
Attack             50
Defense            45
Sp. Atk           135
Sp. Def            95
Speed             120

In [21]:
df.loc[df['Type 1'] == 'Fire']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage,Legendary
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,2,False
5,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,3,False
36,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
37,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,2,False
57,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
58,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,2,False
76,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
77,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,2,False
125,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
135,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,2,False
145,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True

In [24]:
df.loc[df['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,2,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,3,False
42,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
43,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,2,False
44,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,3,False
68,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
69,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,2,False
70,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,3,False
101,102,Exeggcute,Grass,Psychic,325,60,40,80,60,45,40,1,False
102,103,Exeggutor,Grass,Psychic,520,95,95,85,125,65,55,2,False
113,114,Tangela,Grass,NaN,435,65,55,115,100,40,60,1,False

In [25]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage
count,151.000000,151.00000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000
mean,76.000000,407.07947,64.211921,72.549669,68.225166,67.139073,66.019868,68.933775,1.582781
std,43.734045,99.74384,28.590117,26.596162,26.916704,28.534199,24.197926,26.746880,0.676832
min,1.000000,195.00000,10.000000,5.000000,5.000000,15.000000,20.000000,15.000000,1.000000
25%,38.500000,320.00000,45.000000,51.000000,50.000000,45.000000,49.000000,46.500000,1.000000
50%,76.000000,405.00000,60.000000,70.000000,65.000000,65.000000,65.000000,70.000000,1.000000
75%,113.500000,490.00000,80.000000,90.000000,84.000000,87.500000,80.000000,90.000000,2.000000
max,151.000000,680.00000,250.000000,134.000000,180.000000,154.000000,125.000000,140.000000,3.000000

In [28]:
df.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage,Legendary
40,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
144,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
39,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,2,False
109,110,Weezing,Poison,NaN,490,65,90,120,85,70,60,2,False
69,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,2,False
23,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,2,False
64,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,3,False
141,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
62,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False

In [32]:
df.sort_values(['Type 1', 'HP'], ascending=True)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage,Legendary
45,46,Paras,Bug,Grass,285,35,70,55,45,55,25,1,False
12,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
9,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
13,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,2,False
10,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,87,Dewgong,Water,Ice,475,90,70,80,70,95,70,2,False
79,80,Slowbro,Water,Psychic,490,95,75,110,100,80,30,2,False
129,130,Gyarados,Water,Flying,540,95,125,79,60,100,81,2,False
130,131,Lapras,Water,Ice,535,130,85,80,85,95,60,1,False
133,134,Vaporeon,Water,NaN,525,130,65,60,110,95,65,2,False

In [33]:
df.sort_values(['Type 1', 'HP'], ascending=[1,0])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage,Legendary
48,49,Venomoth,Bug,Poison,450,70,65,60,90,75,90,2,False
122,123,Scyther,Bug,Flying,500,70,110,80,55,80,105,1,False
14,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,3,False
126,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
11,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
97,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
115,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
119,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
128,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False

In [37]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,2,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,3,False
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,2,False